build: Support bitbake
LDFLAGS can be defined from outside

This will fix observed issues:

    Subprocess output:arm-poky-linux-musleabi-strip:
    /.../demo: file format not recognized

    ERROR: lvgl-0.0.0-r012 do_package_qa:
    QA Issue: File /usr/lib/lvgl/bin/demo in package lvgl
    doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

Relate-to: https://github.com/lvgl/lvgl/issues/2534
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>